<?php

use Illuminate\Database\Seeder;

class DataTypesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('data_types')->delete();
        
        \DB::table('data_types')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'users',
                'slug' => 'users',
                'display_name_singular' => 'User',
                'display_name_plural' => 'Users',
                'icon' => 'voyager-person',
                'model_name' => 'TCG\\Voyager\\Models\\User',
                'policy_name' => 'TCG\\Voyager\\Policies\\UserPolicy',
                'controller' => 'TCG\\Voyager\\Http\\Controllers\\VoyagerUserController',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-03 13:48:39',
                'updated_at' => '2020-03-03 13:48:39',
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'menus',
                'slug' => 'menus',
                'display_name_singular' => 'Menu',
                'display_name_plural' => 'Menus',
                'icon' => 'voyager-list',
                'model_name' => 'TCG\\Voyager\\Models\\Menu',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-03 13:48:39',
                'updated_at' => '2020-03-03 13:48:39',
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'roles',
                'slug' => 'roles',
                'display_name_singular' => 'Role',
                'display_name_plural' => 'Roles',
                'icon' => 'voyager-lock',
                'model_name' => 'TCG\\Voyager\\Models\\Role',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-03 13:48:39',
                'updated_at' => '2020-03-03 13:48:39',
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'categories',
                'slug' => 'categories',
                'display_name_singular' => 'Category',
                'display_name_plural' => 'Categories',
                'icon' => 'voyager-categories',
                'model_name' => 'TCG\\Voyager\\Models\\category',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-03 13:48:58',
                'updated_at' => '2020-03-10 07:57:36',
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'posts',
                'slug' => 'posts',
                'display_name_singular' => 'Post',
                'display_name_plural' => 'Posts',
                'icon' => 'voyager-news',
                'model_name' => 'App\\Models\\Post',
                'policy_name' => 'TCG\\Voyager\\Policies\\PostPolicy',
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"desc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-03 13:49:01',
                'updated_at' => '2020-03-10 10:39:48',
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'pages',
                'slug' => 'pages',
                'display_name_singular' => 'Page',
                'display_name_plural' => 'Pages',
                'icon' => 'voyager-file-text',
                'model_name' => 'TCG\\Voyager\\Models\\Page',
                'policy_name' => NULL,
                'controller' => '',
                'description' => '',
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => NULL,
                'created_at' => '2020-03-03 13:49:03',
                'updated_at' => '2020-03-03 13:49:03',
            ),
            6 => 
            array (
                'id' => 8,
                'name' => 'subscribenewsletters',
                'slug' => 'subscribenewsletters',
                'display_name_singular' => 'Subscribenewsletter',
                'display_name_plural' => 'Subscribenewsletters',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Subscribenewsletter',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-03-08 07:14:19',
                'updated_at' => '2020-03-08 07:14:19',
            ),
            7 => 
            array (
                'id' => 9,
                'name' => 'contacts',
                'slug' => 'contacts',
                'display_name_singular' => 'Contact',
                'display_name_plural' => 'Contacts',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Contact',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-09 08:31:22',
                'updated_at' => '2020-03-09 08:41:22',
            ),
            8 => 
            array (
                'id' => 11,
                'name' => 'homesliders',
                'slug' => 'homesliders',
                'display_name_singular' => 'Homeslider',
                'display_name_plural' => 'Homesliders',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Homeslider',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-03-09 14:28:09',
                'updated_at' => '2020-03-09 14:28:09',
            ),
            9 => 
            array (
                'id' => 14,
                'name' => 'category_post',
                'slug' => 'category-post',
                'display_name_singular' => 'Category Post',
                'display_name_plural' => 'Category Posts',
                'icon' => NULL,
                'model_name' => 'App\\Models\\CategoriesPost',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-03-10 07:55:13',
                'updated_at' => '2020-03-10 07:55:13',
            ),
            10 => 
            array (
                'id' => 15,
                'name' => 'abouts',
                'slug' => 'abouts',
                'display_name_singular' => 'About',
                'display_name_plural' => 'Abouts',
                'icon' => NULL,
                'model_name' => 'App\\Models\\About',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-10 14:20:17',
                'updated_at' => '2020-03-10 14:23:26',
            ),
            11 => 
            array (
                'id' => 17,
                'name' => 'staff',
                'slug' => 'staff',
                'display_name_singular' => 'Staff',
                'display_name_plural' => 'Staff',
                'icon' => NULL,
                'model_name' => 'App\\Models\\staff',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null,"scope":null}',
                'created_at' => '2020-03-10 15:02:07',
                'updated_at' => '2020-03-10 15:36:23',
            ),
            12 => 
            array (
                'id' => 18,
                'name' => 'getinvolveds',
                'slug' => 'getinvolveds',
                'display_name_singular' => 'Getinvolved',
                'display_name_plural' => 'Getinvolveds',
                'icon' => NULL,
                'model_name' => 'App\\Models\\Getinvolved',
                'policy_name' => NULL,
                'controller' => NULL,
                'description' => NULL,
                'generate_permissions' => 1,
                'server_side' => 0,
                'details' => '{"order_column":null,"order_display_column":null,"order_direction":"asc","default_search_key":null}',
                'created_at' => '2020-03-11 12:10:58',
                'updated_at' => '2020-03-11 12:10:58',
            ),
        ));
        
        
    }
}